export { default as BasedTemplate } from './BasedTemplate/templates';
export { default as EventCreate } from './EventCreate';
export { default as EventDetail } from './EventDetail';
export { default as EventJoin } from './EventJoin';
export { default as Login } from './Login';
export { default as Main } from './Main';
export { default as MyPage } from './MyPage';
export { default as NotFound } from './NotFound';
export { default as SignUp } from './SignUp';
