version: '3.7'
services:
  db:
    image: jdd04026/mariadb-locale:latest
    container_name: bu-db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PW}
    ports:
      - '${DB_PORT}:3306'

  redis:
    image: redis:5.0.7-alpine
    container_name: bu-redis
    volumes:
      - redisdata:/data
    ports:
      - '${REDIS_PORT}:6379'


volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
